---

- name: "Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Include Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Include Tasks: Default"
  ansible.builtin.include_tasks: "default.yml"
  when: not distribution_config.stat.exists

- name: Copy fish_plugins file
  ansible.builtin.copy:
    dest: ~/.config/fish/fish_plugins
    src: fish_plugins
  register: copy_fish_plugins

- name: Check if fisher exists
  ansible.builtin.stat:
    path: ~/.config/fish/functions/fisher.fish
  register: fisher_stat

- name: Init fisher
  ansible.builtin.shell:
    executable: fish
    cmd: curl -sL https://git.io/fisher | source && fisher update
  register: fisher_init
  when: not fisher_stat.stat.exists

- name: Fisher update plugins
  ansible.builtin.shell:
    executable: fish
    cmd: fisher update
  when: copy_fish_plugins.changed and not fisher_init.changed

- name: Copy fish config file
  ansible.builtin.copy:
    dest: ~/.config/fish/config.fish
    src: config.fish

- name: Copy all autoload functions
  ansible.builtin.copy:
    dest: ~/.config/fish/functions/
    src: functions/

- name: Check if theme exists
  ansible.builtin.lineinfile:
    line: SETUVAR fish_color_normal:cdd6f4
    path: ~/.config/fish/fish_variables
    state: present
  register: theme_grep

- name: Select theme
  ansible.builtin.shell:
    executable: fish
    cmd: echo y | fish_config theme save "Catppuccin Mocha"
  when: theme_grep.changed

- name: Ensure fish is set as default login shell
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/bin/fish
    state: present
