---

- name: Dotfiles
  hosts: all
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Gatther fact subset
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - system

    - name: Detect Bitwarden
      ansible.builtin.import_tasks: pre_tasks/detect_bitwarden.yml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      loop: "{{ run_roles }}"
      tags:
        - always
