---

- name: Ensure .ssh directory exists and has correct permissions
  ansible.builtin.file:
    mode: 0700
    path: ~/.ssh
    state: directory

- name: Ensure .ssh/conf.d directory exists
  ansible.builtin.file:
    path: ~/.ssh/conf.d
    state: directory

- name: Ensure .ssh/control directory exists
  ansible.builtin.file:
    path: ~/.ssh/control
    state: directory

- name: Ensure ssh config exists
  ansible.builtin.template:
    dest: ~/.ssh/config
    src: config.j2

- name: Copy misc ssh config
  ansible.builtin.copy:
    dest: ~/.ssh/conf.d/02-misc.conf
    src: 02-misc.conf
