---

- name: Ensure kitty is installed
  ansible.builtin.package:
    name: kitty
    state: present

- name: Create Catpuccin Mocha theme config
  ansible.builtin.shell:
    cmd: kitty +kitten themes --dump-theme Catppuccin-Mocha > ~/.config/kitty/Catppuccin-Mocha.conf
    creates: ~/.config/kitty/Catppuccin-Mocha.conf

- name: Copy ssh kitten config file
  ansible.builtin.copy:
    dest: ~/.config/kitty/ssh.conf
    src: ssh.conf

- name: Copy kitty config file
  ansible.builtin.copy:
    dest: ~/.config/kitty/kitty.conf
    src: kitty.conf
