---

- name: Install Zen browser
  community.general.flatpak:
    name: app.zen_browser.zen
    method: user
    state: present

- name: Set default Browser to Zen
  ansible.builtin.command:
    cmd: "xdg-mime default app.zen_browser.zen.desktop {{ item }}"
  changed_when: false
  loop:
    - text/html
    - application/xhtml+xml
    - x-scheme-handler/http
    - x-scheme-handler/https
