---

- name: "Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Include Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: Ensure ghostty config directory exists
  ansible.builtin.file:
    path: ~/.config/ghostty
    state: directory

- name: Copy ghostty config
  ansible.builtin.copy:
    dest: ~/.config/ghostty/config
    src: config
