---

- name: Install Bitwarden Desktop
  community.general.flatpak:
    name: com.bitwarden.desktop
    method: user
    state: present

- name: Copy desktop file
  ansible.builtin.copy:
    dest: ~/.local/share/applications/com.bitwarden.desktop.desktop
    src: com.bitwarden.desktop.desktop
