---
# tasks file for essentials

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure 'Hack' font exists
  ansible.builtin.package:
    name: "{{ hack_font_package_name }}"
    state: present

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.local/bin"
    state: directory

- name: Add notification to drink water
  ansible.builtin.cron:
    hour: '*/2'
    job: XDG_RUNTIME_DIR="/run/user/$(/usr/bin/id -u)" /usr/bin/notify-send -u critical -i ~/.config/dotfiles/roles/essentials/files/water-bottle.png "Erinnerung" "Trink was Junge!" &> /dev/null
    minute: 7
    name: drink-reminder
    state: present

# - name: Set password for normal user
#   ansible.builtin.user:
#     state: present
#     name: "{{ user.name }}"
#     password: "{{ user.password }}"

# - name: Set root password
#   ansible.builtin.user:
#     name: root
#     state: present
#     password: "{{ root_password }}"

# - name: Set hostname
#   ansible.builtin.hostname:
#     name: "{{ hostname }}"
#     use: systemd

# - name: Add SSH keys
#   when: user.ssh_keys is defined

# - name: Create SSH key
#   ansible.builtin.user:
#     state: present
#     name: "{{ user.name }}"
#     generate_ssh_key: true
#     ssh_key_type: ed25519
#     ssh_key_comment: "{{ user.name }}@{{ hostname }}"
#     ssh_key_passphrase: "{{ user.ssh_key_password }}"
#   when: user.ssh_keys is not defined and user.ssh_key_password is defined

# - name: Install basic binaries
#   ansible.builtin.package:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - git
#     - curl
#     - vim
#     - ncdu
