---

- name: "Default: Ensure nvim is installed"
  ansible.builtin.package:
    name: neovim
    state: present
  when: not distribution_config.stat.exists

- name: "Default: Ensure nvim init config exists"
  ansible.builtin.copy:
    dest: ~/.config/nvim/init.vim
    src: init.vim
  when: not distribution_config.stat.exists
