---

- name: Ensure nvim config directory exists
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: Ensure nvim init config exists
  ansible.builtin.copy:
    dest: ~/.config/nvim/init.vim
    src: init.vim
