---

- name: Ensure nvim is installed
  ansible.builtin.package:
    name: neovim
    state: present

- name: Ensure nvim init config exists
  ansible.builtin.copy:
    dest: ~/.config/nvim/init.vim
    src: init.vim
